config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
  resources :orders
  resources :line_items
  resources :carts
  
  get "menu/index"
  resources :menu_items do
    get :who_bought, on: :member
  end
  
  post "line_items/update"

  root 'menu#index', as: 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_item
  belongs_to :cart
  
  def total_price
    menu_item.price * quantity
  end
  
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json

  def create
    menu_item = MenuItem.find(params[:menu_item_id])
    @line_item = @cart.add_menu_item(menu_item.id) # @cart is actually Cart Model
    quantity = params[:quantity]

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.json  { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json  { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
   end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])
    @line_item.quantity = params[:item][:quantity]
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:menu_item_id)
    end

    def line_items_params
      params.require(:line_item).permit(:quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_item_id %><br>
    <%= f.text_field :menu_item_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<table>
  <tr>
    <th>Quantity</th>
    <th>Product Name</th>
    <th>Size</th>
    <th>Price</th>
  </tr>
<% @cart.line_items.each do |item| %>
  <tr>
    <td>
      <%= form_for :item, :url => line_items_update_path(id: item.id) do |f| %>
        <div class="field">
          <%= f.number_field :quantity, value: item.quantity, class: 'qty-field' %>
          <%= submit_tag "Update" %>
        </div>
      <% end %>
    </td>
    <td><%= line_item.menu_item.title %></td>
      <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
      <td><%= button_to 'x', line_item, method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
<% end %>
    <tr>
        <td colspan="3">Total Price</td>
        <td><%= number_to_currency(@cart.total_price) %></td>
    </tr>
</table>

app/views/line_items/create.js.erb
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Menu item</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.menu_item %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu item:</strong>
  <%= @line_item.menu_item %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>